apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - bifrost-deployment.yaml
  - bifrost-service.yaml
  - bifrost-configmap.yaml
  - opensandbox-deployment.yaml
  - opensandbox-service.yaml
  - opensandbox-rbac.yaml
