apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensandbox
spec:
  template:
    spec:
      containers:
        - name: opensandbox
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
