apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: opensandbox-config
    files:
      - sandbox.toml=config.kubernetes.toml

generatorOptions:
  disableNameSuffixHash: true
